### ISSUE TITLE
About SongbookUpdater.jar

### ISSUE THREAD

**Issue by Zedrock** [Greonyral/stone#1]
Hello,
i use standalone version for SongbookUpdater.jar since a while now and it's very useful for me. I have so many .abc files with many versions of them to make many checks (more than 15000 .abc files now).

But, 
since i moved the repertory : C:/users/accountname/documents/The Lord of the Rings Online (and all needed subfolders) on an other drive 
H:/users/accountname/documents/The Lord of the Rings Online, 
SongbookUpdater don't want to work.
More precisely, it works but do nothing. No SongbookUpdateData.zip is generated.

I try with integrated one in SToNe and i got this error message : 
"The default path or the path defined in the config-file does not exist: "Users\
accountname\Documents\The Lord of the Rings Online\Music". Please look into the
manual for more information.
I try to modify .SToNe config file without success. Still having the same error message from SToNe.

In an other way, for example, Chiran's songbook.hta is still working. Same for SongbookFiller.exe from SongbookBB. But i don't want to use them, they are too slow to generate the songbook data file for my own. They are both in H:/users/accountname/documents/The Lord of the Rings Online/Pluginsdata rep.

Can you take a look on this.

I know I should have to change the path in the configuration file but that does not change anything. Did I miss something?

Thank you for this useful utility i used may often.

Zed'Bara Bahau'Rock from Landroval

**Comment by Greonyral** [comment]
Hi Zedrock,

I use the Windows variable %UserProfile% to determine the position of
the "The Lord of the Rings Online". In your case it should point to
"H:/users/accountname". You saw already that you can adjust he default
path with a config file. The small sized SongbookUpdater however isn't
supporting this feature. The new versions of SToNe are using
SToNE/launch.cfg.txt instead of .SToNe
Best is to download latest version of the program SToNe.jar from
https://drive.google.com/open?id=0B9Wzh5LxIue1b0FTOFh2MHp5M00 - it has
auto-update functionality and bundles the additional features i created

Nelphindal
of Dwarrowdelf
Member of a Rock And A Hard Place

Am 24.07.2015 um 02:07 schrieb Zedrock:

> Hello,
> i use standalone version for SongbookUpdater.jar since a while now and
> it's very useful for me. I have so many .abc files with many versions
> of them to make many checks (more than 15000 .abc files now).
> 
> But,
> since i moved the repertory : C:/users/accountname/documents/The Lord
> of the Rings Online (and all needed subfolders) on an other drive
> H:/users/accountname/documents/The Lord of the Rings Online,
> SongbookUpdater don't want to work.
> More precisely, it works but do nothing. No SongbookUpdateData.zip is
> generated.
> 
> I try with integrated one in SToNe and i got this error message :
> "The default path or the path defined in the config-file does not
> exist: "Users\
> accountname\Documents\The Lord of the Rings Online\Music". Please look
> into the
> manual for more information.
> I try to modify .SToNe config file without success. Still having the
> same error message from SToNe.
> 
> In an other way, for example, Chiran's songbook.hta is still working.
> Same for SongbookFiller.exe from SongbookBB. But i don't want to use
> them, they are too slow to generate the songbook data file for my own.
> They are both in H:/users/accountname/documents/The Lord of the Rings
> Online/Pluginsdata rep.
> 
> Can you take a look on this.
> 
> I know I should have to change the path in the configuration file but
> that does not change anything. Did I miss something?
> 
> Thank you for this useful utility i used may often.
> 
> Zed'Bara Bahau'Rock from Landroval
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Greonyral/stone/issues/1.

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by Zedrock** [comment]
Thank a lot for your fast answer.

Ok, i used last version of SToNe.jar (maybe 7.7.1 ?) you sent me.
Then I fixed my path for the "The Lord of the Rings Online" on H:/ in the new confg-file launch.cfg.txt.
Hurra! SToNe Songbookupdater find my /Music directory now and generates SongbookUpdateData.idx in /PluginsData :)

So, I will use it in this version but i wish to summit you 3 things :
- It's not so easy to find SToNe directory to fix config-file. At home, It's in C:\Users\nameaccount\AppData\Roaming\SToNe. Usually, users never need to go in AppData\Roaming.
- Because i'm not expecting to use others SToNe tools, except SongbookUpdater, i will be very happy to have a stand-alone version of it. I got my own workspace for using BruTE. So, I encourage you to make a stand-alone version^^. By now, through SToNe, after it checked updates, i need three clics to update my Songbook files list (instead one before^^).
- That said, i tried to use AbcCreator to see how it deals with BRuTe but i got an error.
  SToNe displays : java.lang.reflect.UndeclaredThrowableException.
  It created subfolder brute (under SToNe) with drummaps, library.zip, midi2abc.exe, midival.exe, remap.exe and VERSION... but nothing more. Any idea of what happened ?

Best regards

Zed'The boring rockin'Dorf!

**Comment by Greonyral** [comment]
Hello Zed

Many thanks for you feed back.

> Thank a lot for your fast answer.
> 
> Ok, i used last version of SToNe.jar (maybe 7.7.1 ?) you sent me.
> Then I fixed my path for the "The Lord of the Rings Online" on H:/ in
> the new confg-file launch.cfg.txt.
> Hurra! SToNe Songbookupdater find my /Music directory now and
> generates SongbookUpdateData.idx in /PluginsData :)
> 
> So, I will use it in this version but i wish to summit you 3 things :
> 
>  *
> 
> ```
> It's not so easy to find SToNe directory to fix config-file. At
> home, It's in C:\Users\nameaccount\AppData\Roaming\SToNe. Usually,
> users never need to go in AppData\Roaming.
> ```
> 
> Im aware of it but i have to put somewhere the file. I did not want to
> place it at C:\Users<name>\Documents for some reason. You get to
> C:\Users<name>\AppData\Roaming by the short path %appdata%. Where as
> finding the path to Documents have been implemented buggy - exspecially
> on Vista. (And normally the config file is edited not that often)
> 
>  *
> 
> ```
> Because i'm not expecting to use others SToNe tools, except
> SongbookUpdater, i will be very happy to have a stand-alone
> version of it. I got my own workspace for using BruTE. So, I
> encourage you to make a stand-alone version^^. By now, through
> SToNe, after it checked updates, i need three clics to update my
> Songbook files list (instead one before^^).
> ```
> 
> The (n)one click required standalone version needs an modified source
> which causes extra work to maintain. I will have a look on it again if I
> can convert it in a way for easy building.
> 
>  *
> 
> ```
> That said, i tried to use AbcCreator to see how it deals with
> BRuTe but i got an error.
> SToNe displays : java.lang.reflect.UndeclaredThrowableException.
> It created subfolder brute (under SToNe) with drummaps,
> library.zip, midi2abc.exe, midival.exe, remap.exe and VERSION...
> but nothing more. Any idea of what happened ?
> ```
> 
> I tried to reproduce but i dont get the error. Does it happen once or
> always - or somewhere between?
>  SToNe creates a log file ( %appdata%\SToNe\log.txt ). It should contain
> some information for debugging when errors occur.
> 
> Best regards
> 
> Zed'The boring rockin'Dorf!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/Greonyral/stone/issues/1#issuecomment-125046020.
> 
> Cheers

Nelphi

---

Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus
